config/routes.rb
SurveyAdmin::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users

  resources :home, only: [:index] do
    get :welcome, on: :collection
    get :about_research, on: :collection
    get :about_media, on: :collection
    match :contact_us, on: :collection
    match :set_language, on: :collection    
  end
  
  resources :surveys do
    match :results
    match :question
    match :question_info
    match :question_lang
    get   :share, on: :collection
    get   :share_list
    post  :invite, on: :collection
    get :autocomplete_state_name, :on => :collection
  end
  
  resources :survey_notifications do
    get :check_new, on: :collection
  end

  root :to => 'home#index'
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  attr_accessible :audience_description, :description, :document, :title, :user_id, :active, :goal
  attr_accessible :survey_questions_attributes
  
  mount_uploader :document, DocumentUploader

  validates_presence_of :user_id, :title, :audience_description, :description
  validates_uniqueness_of :title

  default_scope order('id ASC')
  
  belongs_to :user
  
  has_many :survey_questions, dependent: :destroy
  has_many :survey_user_permissions, dependent: :destroy
  has_many :survey_notifications, dependent: :destroy
  has_many :survey_completes, dependent: :destroy

  accepts_nested_attributes_for :survey_questions, :allow_destroy => true, :reject_if => :all_blank
  
  scope :active, where(active: true)
  scope :inactive, where(active: false)

  def to_s
    title
  end
  
  def survey_possible_answers
    @survey_possible_answers ||= SurveyPossibleAnswer.includes(:survey_question).where(survey_question_id: self.survey_question_ids)
  end

  def survey_user_answers
    @survey_user_answers ||= SurveyUserAnswer.includes(:survey_possible_answer).where(survey_possible_answer_id: self.survey_possible_answers.map(&:id))
  end

  def generate_token(user)
    Digest::MD5.hexdigest("#{user.id}#{user.created_at}#{id}#{created_at}")
  end
end

app/models/survey_graph_type.rb
class SurveyGraphType < ActiveRecord::Base
  attr_accessible :description, :name

  validates_presence_of :name, :description
  validates_uniqueness_of :name

  has_many :survey_questions
  
  def to_s
    name
  end
end

app/controllers/surveys_controller.rb
require 'json'

class SurveysController < ApplicationController
  before_filter :authenticate_user!, except: [:question_lang, :question_info, :question]
  before_filter :load_survey, only: [:show, :destroy, :edit, :results, :question, :invite, :share_list, :question_lang, :question_info]
  before_filter :load_user_by_survey_token, only: [:question_lang, :question_info, :question]
  autocomplete :state, :name
  
   def results
    create_custom_filters(params)

    @information = {
        :gender => { :male =>0, :female => 0},
        :age => {
            :group1 => {:from=> '18', :to => '24', :value => 0},
            :group2 => {:from=> '25', :to => '34', :value => 0},
            :group3 => {:from=> '35', :to => '44', :value=> 0},
            :group4 => {:from=> '45', :to => '54', :value => 0},
            :group5 => {:from=> '55', :to => '64', :value => 0},
            :group6 => {:from=> '65+', :to => '', :value => 0}
        },
        :total => 0
    }

    @user_ids.each do |user|
      user = User.find(user)
      @information[:total] += 1
      case user.gender
        when 'male'
          @information[:gender][:male] += 1
        when 'female'
          @information[:gender][:female] += 1
      end
      [18..24, 25..34, 35..44, 45..54, 55..64, 65..1.0/0].each_with_index do |range, index|
        @information[:age][:"group#{index+1}"][:value] += 1 if user.age.present? && (range.include? user.age)
      end
    end
    @information[:total] == 0 ? @information[:divide] = 1 : @information[:divide] = @information[:total]
  end



  def index
    authorize! :read, Survey
    @surveys = Survey.accessible_by(current_ability)
  end


  def show
    authorize! :read, Survey
    respond_to do |format|
      format.html
      format.xls
    end
  end

  def new
    @survey = Survey.new
  end

  def create
    authorize! :manage, Survey
    @survey = current_user.surveys.build(params[:survey])
puts @users.class()

    if @survey.save
      # make 4 default questions
      @survey.survey_questions.create( survey_question_type_id: 11, survey_graph_type_id: 1, text: 'Welcome', english_translation: 'Welcome',order: -5 )
      @survey.survey_questions.create( survey_question_type_id: 12, survey_graph_type_id: 1, text: 'Qualified', english_translation: 'Qualified', order:-3)
      @survey.survey_questions.create( survey_question_type_id: 13, survey_graph_type_id: 1, text: 'Declined', english_translation: 'Declined', order:-1 )
      @survey.survey_questions.create( survey_question_type_id: 1, survey_graph_type_id: 1, text: 'First Question', english_translation: 'First Question', order: 1 )

      UserMailer.survey_creation_email(current_user, @survey).deliver
      redirect_to surveys_path, notice: I18n.t("surveys.msg_create_success")
    else
      render action: "new"
    end
  end

  def edit
    authorize! :manage, Survey
  end

  def update
    authorize! :manage, Survey

    if @survey.update_attributes(params[:survey])
      redirect_to surveys_path, notice: I18n.t("surveys.msg_update_success")
    else
      render action: "edit"
    end
  end

  def destroy
    authorize! :manage, Survey
  end


  def question_lang
      load_user_by_survey_token
      puts "FNG 1"
    if @user.nil?
      puts "FNG 1 +i"
      #redirect_to survey_question_path(@survey)
      return
    end
      puts "FNG 2"

    if params[:locale].present?
      session[:locale] = params[:locale]
       if current_user==@user
        puts "Test 1"
        redirect_to survey_question_path(@survey)
       else
        redirect_to survey_question_info_path(@survey, survey_token: params[:survey_token], user_id: params[:user_id], eo: params[:eo], back_url: params[:back_url])
        puts "Test 2"
      end
    else
      render "surveys/question_lang", layout: 'layouts/survey_question'
      puts "Test 3"
    end
  end

  def question_info
      puts "Test 3.14 (pie!)"
    if @user.nil?
      render "surveys/questions/question_finish", layout: 'layouts/survey_question'
      puts "Test 4"
      return
    end
    if request.method == 'POST'
        puts "Test 4.8"

      if @user.update_attributes(params[:user])
        puts "Test 5"

        redirect_to survey_question_path(@survey, survey_token: params[:survey_token], user_id: params[:user_id], eo: params[:eo], back_url: params[:back_url])
        puts "Test 5.4"
      else
        puts "Test 6"
        render "surveys/question_info", layout: 'layouts/survey_question'
        puts "Test 6.4"
      end
    else
      puts "Test 7"

      render "surveys/question_info", layout: 'layouts/survey_question'
      puts "Test 7.4"
    end
  end

  def question
      puts "Test A.1"

    if @user.nil?
        puts " Test  ha?"
      flash.now[:notice] = I18n.t("surveys.msg_survey_permission")
      render "surveys/questions/question_finish", layout: 'layouts/survey_question'
      return
    end
      puts "Test A.2"

    if params[:question_id].blank?
      @question = @survey.survey_questions.order("id asc").first
      @question.step_number = 1
      render_question()
      return
    end
      puts "Test A.3"

    prev_question = SurveyQuestion.find(params[:question_id]).convert_to_child_class
    prev_question.step_number = params[:step_number]
      puts "Test A.5"

    # qualified/declined
    if [12, 13].include?(prev_question.survey_question_type_id)
      SurveyComplete.create(user_id: @user.id, survey_id: @survey.id, done_by_eo: params[:eo] == 'true')
      puts "Test A.7"

      if current_user
        redirect_to surveys_path
      else
        redirect_to params[:back_url].empty? ? root_path : params[:back_url]
      end
      puts "Test A.8"

      return
    end

    # validation check
    unless prev_question.validate?(params)
      @question = prev_question
      render_question()
      return
    end

    # submit question
    @question = prev_question.submit(@user, params, true)

    # next question checking
    if @question.present?
      @question.step_number = params[:step_number].to_i + 1

      render_question()
    else
      SurveyComplete.create(user_id: @user.id, survey_id: @survey.id, done_by_eo: params[:eo] == 'true')
      flash.now[:notice] = I18n.t("surveys.msg_no_next_question")
      render "surveys/questions/question_finish", layout: 'layouts/survey_question'
    end

  end

  def share
    @surveys = current_user.surveys + current_user.invitable_shared_surveys
  end

  def share_list
    render partial: 'share_survey'
  end

  def invite
    new_user_flag = false
    user = User.find_by_email(params[:invite_email])

    if user.nil?
      user = User.create!(email: params[:invite_email], password: User.reset_password_token, role: "client")
      new_user_flag = true
    elsif user.id == @survey.user_id
      render json: {success: false, message: I18n.t("surveys.msg_access_duplication")}
      return
    end

    if user.valid?
      if SurveyUserPermission.where(user_id: user.id, survey_id: @survey.id).first.nil?
        SurveyUserPermission.create(user_id: user.id, survey_id: @survey.id, invite: true)
        SurveyNotification.create(user_id: user.id, text: "#{current_user.to_s} le ha enviado una invitacion para que usted vea los resultados de la nueva encuesta.", english_translation: "#{current_user.to_s} has invited you to see the results for a new survey.", survey_id: @survey.id)
        UserMailer.invite_survey_to_user(current_user, user, params[:invite_message], @survey, new_user_flag).deliver
        render json: {success: true}
      else
        render json: {success: false, message: I18n.t("surveys.msg_access_duplication")}
      end
    else
      render json: {success: false, message: I18n.t("surveys.msg_invitation_failed")}
    end
  end


  def load_survey
    @survey = params[:id].nil? ? Survey.find(params[:survey_id]) : Survey.find(params[:id])
  end

  def render_question(message = nil)
    flash.now[:alert] = message if message
puts " Test B "+@question.to_s + "   B"
    respond_to do |format|
      format.html do
        render :question, layout: 'layouts/survey_question'
      end
    end
  end

  def load_user_by_survey_token

    if params[:survey_token].present?
      @user = User.find_by_id(params[:user_id])
      unless @user.nil?
        @user = nil if params[:survey_token] != @survey.generate_token(@user)
      end
    else
        @user=current_user
    end
if @user.nil?

puts "so confused"
puts "Test"
puts  params[:survey_token]
puts   User.find_by_id(params[:user_id])
puts params[:survey_token].present?
end


    if current_user.nil? and @user.nil?
        flash.now[:notice] = I18n.t("surveys.msg_survey_permission")
        render "surveys/questions/question_finish", layout: 'layouts/survey_question'
        puts "UnAuthorised acceess"
         return
    end
    end

  def create_custom_filters(params)
    user_ids = {}; answer_ids = {}
    @survey_questions = @survey.survey_questions.where("survey_question_type_id NOT IN (11, 12, 13)").includes(:survey_possible_answers, :survey_user_answers )
    filter = JSON.parse(params[:filterItems]) if params[:filterItems]
    @survey_questions.each do |question|
      question.survey_user_answers.includes(:user).each do |answer|
        next if answer.user.blank?
        expression = true
        if params.present? && params[:filterItems]
          filter.each do |key,value|
            case key
              when 'fromdate'
                expression &= answer.created_at >= value
              when 'todate'
                expression &= answer.created_at <= value
              when 'min_age_greator'
                expression &= answer.user.age > value if answer.user.age
              when 'min_age_less'
                expression &= answer.user.age < value if answer.user.age
              when 'gender'
                expression &= answer.user.gender.downcase == value.downcase if answer.user.gender
            end
          end
        end
        if expression

app/helpers/surveys_helper.rb
module SurveysHelper
	def shuffled_colors
		colors = ['green', 'yellow', 'red', 'blue', 'orange', 'purple', 'pink', 'navy']
		colors.shuffle
	end
end

app/views/surveys/_filter_results.html.haml
= form_tag survey_results_path(@survey) do 
  .span12
    %strong 
      = I18n.t("survey_result.fitler_text")
      &nbsp;
    = select_tag :filter_by, options_for_select([I18n.t("survey_result.fitler_text_1"), I18n.t("survey_result.fitler_text_2"), I18n.t("survey_result.fitler_text_3"), I18n.t("survey_result.fitler_text_4")].collect{ |i| [i, i.downcase] }, params[:filter_by]), style: 'width: 120px;', include_blank: true
  #filter-date.date-range.hide.span6{style: 'margin-bottom: 10px;'}
    .pull-left
      %label
        = I18n.t("survey_result.fitler_text_5")
    .input-append.pull-left
      = text_field_tag :filter_from, params[:filter_from], class: 'datepicker filter_item'
      %span.add-on
        %i.icon-th
    .pull-left
      %label
        = I18n.t("survey_result.fitler_text_6")
    .input-append.pull-left
      = text_field_tag :filter_to, params[:filter_to], class: 'datepicker filter_item'
      %span.add-on
        %i.icon-th
  #filter-age-greator.hide.span3
    = I18n.t("survey_result.fitler_text_7")
    = number_field_tag :filter_age_greator, params[:filter_age_greator], class: 'span1 filter_item', size: 2
  #filter-age-less.hide.span3
    = I18n.t("survey_result.fitler_text_7_1")
    = number_field_tag :filter_age_less, params[:filter_age_less], class: 'span1 filter_item', size: 2
  #filter-gender.hide.span3
    = select_tag :filter_gender, options_for_select([I18n.t("survey_result.fitler_text_16"), I18n.t("survey_result.fitler_text_17")].collect{ |i| [i, i.downcase] }, params[:filter_gender]), class: 'span2 filter_item', include_blank: true
  #filter-location.hide.span8
    &nbsp;
    = I18n.t("survey_result.fitler_text_8")
    = autocomplete_field_tag :filter_state, params[:filter_state], autocomplete_state_name_surveys_path, :class => 'span1 filter_item'
    &nbsp;
    = I18n.t("survey_result.filter_text_9")
    = text_field_tag :filter_city, params[:filter_city], class: 'span2 filter_item'
    &nbsp;
    = I18n.t("survey_result.filter_text_10")
    = number_field_tag :filter_zipcode, params[:filter_zipcode], {class: 'span2 filter_item', size: 5}
.span12{:style => "margin-top: 10px;margin-bottom:15px;"}
  %a#add-filter.medium.awesome
    = I18n.t("survey_result.filter_text_11")

%br
.span12
  %p#validation-error.alert{style: "display: none; line-height: 15px;"}
.span12.filter-queries
  %table#filter-queries.table
    %thead
      %tr
        %th
          %strong 
            = I18n.t("survey_result.filter_text_12")
        %th{colspan: 5}
          %strong 
            = I18n.t("survey_result.filter_text_13")
        %th
          %strong
            = "Value"
    %tbody
      %tr
%a#result-search.medium.awesome{ style: "margin-left: 20px; float: left; margin-top: 15px;"}
  = I18n.t("button.search")

app/views/surveys/_form.html.haml
= simple_form_for survey do |f|
  = f.error_notification
  - if alert
    %p.alert 
      = alert

  %fieldset
    .row-fluid
      = f.input :title
  %fieldset
    .row-fluid
      = f.input :audience_description, as: :text
  %fieldset
    .row-fluid
      = f.input :description, as: :text
  %fieldset
    .row-fluid
      = f.input :document, as: :file

  %div
    .span4.pull-right
      = f.button :submit, :class => 'medium awesome'
      &nbsp;
      = link_to I18n.t("header.my_surveys"), surveys_path, :class=> 'medium awesome'

app/views/surveys/_invite_member.html.haml
= form_tag invite_surveys_path, remote: true, id: 'invite_form', :'data-type' => 'json' do
  %p
    #invite_alert.hide
  = text_field_tag :invite_email, '', placeholder: I18n.t("share.text_2"), style: "width: 300px;"
  %br
  %strong Message
  %br
  = text_area_tag :invite_message, '', style: "height: 160px; width: 300px;"
  = hidden_field_tag :survey_id, '', id: 'invite_survey_id'

app/views/surveys/_share_survey.html.haml
%table.table.table-no-borders.table-condensed
  %tr
    %td{colspan: 5}
      %h3= @survey.title
  %tr
    %td= @survey.user.full_name
    %td= @survey.user.user_extension.try(:company)
    %td= @survey.user.user_extension.try(:company_role)
    %td= @survey.user.email
    %td= number_to_phone @survey.user.phone_number
  - @survey.survey_user_permissions.each do |permission|
    %tr
      %td= permission.user.try(:full_name)
      %td= permission.user.try(:user_extension).try(:company)
      %td= permission.user.try(:user_extension).try(:company_role)
      %td= permission.user.try(:email)
      %td= number_to_phone permission.user.try(:phone_number)

app/views/surveys/edit.html.haml
%h1 
  = I18n.t("survey_edit.title")
.row
  .span7
    = render partial: "surveys/form", locals: {survey: @survey }
  .span1
  .span4
    %p
      %strong
        = I18n.t("survey_edit.text_1")
.clear

app/views/surveys/index.html.haml
%h1 
  = I18n.t("survey_index.title")
.row
  .span10
    %table.table
      - @surveys.each do |survey|
        %tr
          %td= link_to survey.title, survey_results_path(survey)
          - if current_user.super_admin? 
            %td= link_to I18n.t("button.edit"),  current_user['admin'] ||current_user.admin ? edit_admin_survey_path(survey):edit_survey_path(survey)
          - else
            %td= current_user.own_survey?(survey) ? link_to(I18n.t("button.edit"),  edit_survey_path(survey)) : I18n.t("survey_index.text_2")
          %td= I18n.l(survey.created_at, format: :long)
          %td= survey.active ? I18n.t("survey_common.active") : I18n.t("survey_common.inactive")
          %td= link_to I18n.t("survey_common.test_survey"), survey_question_lang_path(survey)
          %td= link_to I18n.t("survey_common.view_result"), survey_results_path(survey)
  .clear
= hidden_field_tag :notice, flash[:notice]
= link_to I18n.t("survey_common.create"), new_survey_path, class: 'medium awesome'
.span4.pull-right
  &nbsp;&nbsp;&nbsp;

app/views/surveys/new.html.haml
%h1 
  = I18n.t("survey_create.title")
.row
  .span7
    = render partial: "surveys/form", locals: {survey: @survey }
  .span1
  .span4
    %p
      %strong
        = I18n.t("survey_create.text_1")
.clear

app/views/surveys/question.html.haml
.row 
  .one.columns
  .ten.columns
    #progress_bar.ui-progress-bar.ui-container
      .ui-progress
        %span.ui-label.hide
          = I18n.t("question.progress_step")
          %b.value 1
%h4= @question.text_from_lang(session[:locale])
.grid_24{style: 'border-top:1px solid #c2e9d9; padding-top:10px;'}
.row
.one.columns
.ten.columns
  %br
  - if flash.present?
    .alert-box.alert
      - flash.each do |key, msg|
        = h msg
  = simple_form_for @question, url: survey_question_path(@survey), html: {class: 'question-form'} do |f|
    - if @question.errors.any?
      .alert-box.alert
        - @question.errors.full_messages.each do |msg|
          = msg
          %br
    = render "surveys/questions/question_#{@question.survey_question_type_id}", form: f
    = text_field_tag :other_text, '', class: 'question-input'
    .eight.columns
    .four.columns
      = hidden_field_tag :question_id, @question.id
      = hidden_field_tag :result
      = hidden_field_tag :step_number, @question.step_number
      = hidden_field_tag :survey_token, params[:survey_token]
      = hidden_field_tag :user_id, params[:user_id]
      = hidden_field_tag :eo, params[:eo]
      = hidden_field_tag :back_url, params[:back_url]
      = f.submit [12, 13].include?(@question.survey_question_type_id) ? I18n.t("button.finish") : I18n.t("button.continue"), class: 'button', style: 'float :left'
    .row
  = hidden_field_tag :question_type_id, @question.survey_question_type_id
  = hidden_field_tag :other_answer_id, @question.other_answer_id
  = hidden_field_tag :total_questions_cnt, @question.survey.survey_questions.size - 1

app/views/surveys/question_info.html.haml
%h4 
= I18n.t("question_info.title")
.grid_24{style: 'border-top:1px solid #c2e9d9; padding-top:10px;'}
.row
.one.columns
.ten.columns
  = simple_form_for @user, url: survey_question_info_path(@survey) do |f|
    = f.input :first_name, wrapper_html: {style: 'margin-bottom: 8px;'}, label: I18n.t("question_info.first_name")
    .row
    = f.input :last_name, wrapper_html: {style: 'margin-bottom: 8px;'}, label: I18n.t("question_info.last_name")
    .row
    = f.input :address_line_1, wrapper_html: {style: 'margin-bottom: 8px;'}, label: I18n.t("question_info.address_line_1")
    .row
    = f.input :address_line_2, wrapper_html: {style: 'margin-bottom: 8px;'}, label: I18n.t("question_info.address_line_2")
    .row
    = f.input :city, wrapper_html: {style: 'margin-bottom: 8px;'}, label: I18n.t("question_info.city")
    .row
    = f.input :state, wrapper_html: {style: 'margin-bottom: 8px;'}, label: I18n.t("question_info.state")
    .row
    = f.input :zip , wrapper_html: {style: 'margin-bottom: 8px;'}, label: I18n.t("question_info.zip")
    .row
    = f.input :age, wrapper_html: {style: 'margin-bottom: 8px;'}, label: I18n.t("question_info.age")
    .row
    = f.input :gender, collection: [nil,I18n.t("question_info.gender_male"),I18n.t("question_info.gender_female")].collect{ |i| [i, i] }, input_html: {style: 'width: 100px;'}, include_blank: false, label: I18n.t("question_info.gender")
    .row
    %br
    = f.input :phone_number, wrapper_html: {style: 'margin-bottom: 8px;'}, label: I18n.t("question_info.phone_number")
    .row
    .eight.columns
    .four.columns
      = hidden_field_tag :survey_token, params[:survey_token]
      = hidden_field_tag :user_id, params[:user_id]
      = hidden_field_tag :eo, params[:eo]
      = hidden_field_tag :back_url, params[:back_url]
      = f.submit I18n.t("button.continue"), class: 'button', style: 'float :left'
    %br
.row
%br

app/views/surveys/question_lang.html.haml
%h4 Idioma/language
.grid_24{style: 'border-top:1px solid #c2e9d9; padding-top:10px;'}
.row
.one.columns
.ten.columns
  = link_to "English", params[:survey_token].present? ? survey_question_lang_path(@survey, locale: "en", survey_token: params[:survey_token], user_id: params[:user_id], eo: params[:eo], back_url: params[:back_url]) : survey_question_lang_path(@survey, locale: "en"), class: 'button success small expand'
  %br
  %br
  = link_to "Español", params[:survey_token].present? ? survey_question_lang_path(@survey, locale: "es", survey_token: params[:survey_token], user_id: params[:user_id], eo: params[:eo], back_url: params[:back_url]) : survey_question_lang_path(@survey, locale: "es"), class: 'button success small expand'
.row
%br

app/views/surveys/results.html.haml
- content_for :head do
  = javascript_include_tag "http://code.highcharts.com/highcharts.js"
  = javascript_include_tag "http://code.highcharts.com/modules/exporting.js"
  / = javascript_include_tag "plugins/jquery-jvectormap-1.2.2.min"
  / = javascript_include_tag "jquery-vector-map"


  :coffeescript
    window.question_ids = #{@survey.survey_question_ids}
    window.survey_id = #{@survey.id}
%h1.bold
  #{@survey.title}

%h3.summary-heading Summary
%div.summary
  %div.span3
    %strong.survey-count
      = I18n.t("survey_result.text_1")
      = @information[:total]
  .span3
    %strong
  %div.span3
    %strong.survey-count
      = I18n.t("survey_result.text_2")
      = @survey.goal
.clear

%h3.filter-heading By Gender
%div#wrap-filter-gender
  %div.icons
    %div
      = link_to 'Male', '#', class: 'add-filter-gender male'
    %div
      = link_to 'Female', '#', class: 'add-filter-gender female'
  %div.counts
    %div
      %p
        = "#{@information[:gender][:male]} (#{(@information[:gender][:male]*100.0/@information[:divide]).round(2)}%)"
    %div
      %p
        = "#{@information[:gender][:female]} (#{(@information[:gender][:female]*100.0/@information[:divide]).round(2)}%)"
.clear
%h3.filter-heading By Age
%div#wrap-filter-age
  %div.brackets
    - @information[:age].each do |key, value|
      %div
        = link_to "#{value[:from] + (value[:to].present? ? '-' + value[:to] : '')}", '#', class: "add-filter-age #{'_' + value[:from].gsub('+','')}#{'_' + value[:to] if value[:to].present?}", data: {type: 'age', from: value[:from].gsub('+',''), to: value[:to]}
  %div.data
    - @information[:age].each do |key, range|
      %div
        = "#{range[:value]} (#{(range[:value]*100.0/@information[:divide]).round(2)}%)"
.clear
%h3.filter-heading By Location
%div#wrap-filter-location
  %div#map
  %script
    :plain
      // Set a global variable with values tied to US states that will determine the fill color of each state. 0 will be ligt green, 0.5 medium green, 1 dark green
      window.states_selected = {
        "US-MT": 1,
        "US-CA": 1,
        "US-NY": 1
      }

      // Data that will appear next to the state name on mouseover
      window.states_data = {
        "US-MT": '15 (30%)',
        "US-CA": '10 (20%)',
        "US-NY": '25 (50%)'
      }

      // Cities (location, name, data to be diplayed next to the name)
      window.city_data = [
          {latLng: [41.50, -87.37], name: 'Chicago', data: '5 (10%)'},
          {latLng: [32.46, -96.46], name: 'Dallas', data: '10 (20%)'},
          {latLng: [29.76, -95.36], name: 'Houston', data: '15 (30%)'},
          {latLng: [34.3, -118.15], name: 'Los Angeles', data: '10 (20%)'},
          {latLng: [40.43, -74.00], name: 'New York', data: '10 (20%)'},
          {latLng: [35.77, -78.63], name: 'Raleigh', data: '10 (20%)'},
          {latLng: [33.27, -112.04], name: 'Phoenix', data: '10 (20%)'}
      ]
%p
  = render 'filter_results'
.clear
%br
%br
%p



  - ind = 1
  - @survey_questions.each do |question|
    .span8
      = render "surveys/results/question_#{question.survey_question_type_id}", question: question, ind: ind
    .span4
      = link_to I18n.t("survey_result.text_3"), contact_us_home_index_path(message: "#{@survey.title} : #{question.text_from_lang(session[:locale])}"), class: 'small awesome pull-left'
    .span10{style: "margin-top: -15px;"}
      = hidden_field_tag "question_graph_data_#{question.id}", question.graph_data(session[:locale], @answer_ids)
      = hidden_field_tag "question_graph_type_#{question.id}", question.survey_graph_type.id
      %div{id: "question_chart_#{question.id}", style: 'height: 250px; width: 550px;'}
    - ind += 1
    .clear
    %br
    %br

.clear
= link_to I18n.t("button.edit"), edit_survey_path(@survey), class: 'medium awesome'
&nbsp;&nbsp;
= link_to I18n.t("survey_result.text_4"), surveys_path, class: 'medium awesome'
= link_to I18n.t("button.download_answers"), survey_path(@survey, format: "xls"), class: 'medium awesome'

app/views/surveys/share.html.haml
/%h1 Surveys
.span9
  - @surveys.each do |survey|
    %div{id: "invite_#{survey.id}"}
      - @survey = survey
      = render "share_survey"
    %div{style: 'margin-top: -12px;'}
    = link_to I18n.t("share.text_1"), '#', class: 'medium awesome invite' , data: {survey_id: @survey.id, company: @survey.user.user_extension.try(:company), firstname: @survey.user.first_name, lastname: @survey.user.last_name}
    %br
    %br
#invite_form_div.hide
  = render 'invite_member'