config/routes.rb
SurveyAdmin::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users

  resources :home, only: [:index] do
    get :welcome, on: :collection
    get :about_research, on: :collection
    get :about_media, on: :collection
    match :contact_us, on: :collection
    match :set_language, on: :collection    
  end
  
  resources :surveys do
    match :results
    match :question
    match :question_info
    match :question_lang
    get   :share, on: :collection
    get   :share_list
    post  :invite, on: :collection
    get :autocomplete_state_name, :on => :collection
  end
  
  resources :survey_notifications do
    get :check_new, on: :collection
  end

  root :to => 'home#index'
end

app/views/layouts/_footer.html.haml
.grid_24{style: 'border-top:1px solid #c2e9d9; padding-top:10px;'}
  #left
    %span Copyright © 2013. SABEResPODER. All Rights Reserved.
  .clear
  .bcorp_container
    = link_to image_tag("bcorp_footerlogo.jpg", style: 'position:relative; display:block; float:left; margin-right:10px;'), "http://www.bcorporation.net/saberespoder"
    %span.bcorp_footertext{style: 'display:block; position:relative; float:left; width:500px; color:#b5b4b4; line-height:13px; font-weight:normal;'}
      = I18n.t("footer.text_1")
      %br
      = I18n.t("footer.text_2")
  .vuepoint
    = link_to I18n.t("footer.about_sep_research"), about_research_home_index_path
    |
    = link_to I18n.t("footer.about_sep_media"), about_media_home_index_path
    |
    = link_to I18n.t("footer.about_contact_us"), contact_us_home_index_path

app/views/layouts/_header.html.haml
:coffeescript
  window.user_name = "#{current_user.try(:first_name)}"

#navcontainer.grid_24
  #language
    #tab_container
      - if session[:locale].to_s.downcase == 'es'
        %span.english_tab
          English
      - if session[:locale].to_s.downcase == 'en'
        %span.espanol_tab
          Español
      
  .clear
  .span7
    %ul#nav
      %li
        = link_to I18n.t("header.home"), root_path, class: "#{'current' if controller_name == 'home'}"
        - if user_signed_in?
          = link_to I18n.t("header.my_surveys"), surveys_path, class: "#{'current' if controller_name == 'surveys' and action_name != 'share'}"
          = link_to I18n.t("header.share_survey"), share_surveys_path, class: "#{'current' if controller_name == 'surveys' and action_name == 'share'}"
          = link_to I18n.t("header.notification"), survey_notifications_path, class: "#{'current' if controller_name == 'survey_notifications'}"
          %span#notification_new_size.hide
  .span3
    %ul#nav    
      %li.pull-right
        - if user_signed_in?
          = link_to I18n.t("header.profile"), edit_user_registration_path, class: "#{'current' if controller_name == 'registrations'}"
          = link_to I18n.t("header.logout"), destroy_user_session_path, method: :delete
          &nbsp;
          = I18n.t("header.hello")
          #{current_user.first_name}
        - else
          = link_to I18n.t("header.login"), new_user_session_path
.clear
#logocontainer.grid_8
  = link_to image_tag("saberespoder_logo.jpg"), root_path
#loggercontainer.grid_9
  %p
#logocontainer.grid_7
.clear
.clear

app/views/layouts/_survey_question_footer.html.haml
.grid_24{style: 'border-top:1px solid #c2e9d9; padding-top:10px;'}
  #left
    %strong ©SABEResPODER 2013 

app/views/layouts/_survey_question_header.html.haml
:coffeescript
  window.user_name = "#{current_user.try(:first_name)}"

%nav.top-bar
  .row
    .twelve.columns
      = image_tag 'seplogo.jpg', id: 'logo'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title SurveyAdmin
    = stylesheet_link_tag    "application", :media => "all"
    = stylesheet_link_tag  "http://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css"
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
      = stylesheet_link_tag    "plugins/movingboxes-ie", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield :head
    = render "shared/olark_chat"
    :coffeescript
      window.locale = "#{session[:locale]}"
  %body{ class: "#{controller_name}_#{action_name}" + "#{(defined? @body_class) ? ' '+ @body_class : ' one_col'}" }
    #greenbar_header
    #header.container_24
      = if content_for?(:header); yield(:header); else; render "layouts/header"; end
    .secondary.container_24
      .row-fluid
        - flash.each do |key, msg|
          %p.alert{class: "alert-#{key}"}= h msg
      = yield
      .row
      %br
      =# link_to image_tag("chat.png", size: "18x18", style: 'margin-right:3px;') + "Chat with a representative" , '#', class: 'pull-right'
    #footer.container_24
      = render "layouts/footer"
    = render "shared/modal"

app/views/layouts/survey_question.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title SurveyAdmin
    = stylesheet_link_tag    "survey_question", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = yield :head
    :coffeescript
      window.locale = "#{session[:locale]}"
  %body{ class: "#{controller_name}_#{action_name}" + "#{(defined? @body_class) ? ' '+ @body_class : ' one_col'}" }
    = render "layouts/survey_question_header"
    .row
      .six.columns
        = yield
        .row
        = render "layouts/survey_question_footer"